### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 10m4y**

### CODE REVIEW

**Comment by 10m4y** [comment]
@malaythakur I have raised a PR can u check and let me know if it fits and able to merge

**Comment by malaythakur** [comment]
Hey! @cypher4802  Nice job on the commit! Just a few things that would make the documentation even better:

ENVIRONMENT VARIABLE SETUP: Can we add info on how to set up the environment variables for the backend.

TECH STACKS USED: It would help to list the technologies we used in this project.

BACKEND AND FRONTEND SETUP: Let’s include clear steps for setting up both the backend and frontend, so it’s easier for new contributors."

**Comment by malaythakur** [comment]
I've added a dotenv file in the server directory.  You can refer to it when updating the README to guide newcomers on configuring their setup

**Comment by 10m4y** [comment]
@malaythakur updated client's readme file and created readme  file for backend you can check and tell me about further

**Comment by malaythakur** [comment]
@cypher4802  a repository only contains only one primary README.md file. So do not make different readme.md. For your better understanding i am writing the key features that you should include in the README.

**1. Project Overview**
**2. Tech Stacks**

- Frontend: React, Tailwind CSS
- Backend: Node.js, Express.js
- Database: AWS RDS (MySQL)
- Authentication: JWT
- Payments: Stripe
- Video Hosting: Vimeo API

**3. Environment Setup**
Include a section on how to set up the environment, including necessary environment variables.
Example: Point contributors(developers) to the .env file and provide instructions on obtaining sensitive keys (e.g., AWS RDS details, Stripe keys).

4. Installation Instructions
Step-by-step guide to set up the project locally, including:

- Cloning the repository.
- Installing dependencies (npm install).
- Running the backend and frontend servers.

5. Backend & Frontend Setup
Clarify how to set up and run the backend (Node.js, Express) and frontend (React) independently, if necessary.
Example:

- Backend: npm run server
- Frontend: npm start (for React)

6. Key Features
Highlight the main features:

- User authentication (JWT-based login and registration).
- Course purchase and subscription.
- Course video player.
- Secure payment integration (Stripe).

7. Contributing Guidelines
Explain how others can contribute to the project.
Outline the process for forking, creating branches, and making pull requests.
Example:

- Fork the repository.
- Create a feature branch (git checkout -b feature-name).
- Make changes and commit.
- Open a pull request with proper details.

Feedback on the Recent Pull Request:

1:  We are not using MongoDB and Mongoose
2 :  In env file we have several secret token please refer to it and mention how to get them. USE chatgpt for that one.
3.  No need to mentions these in readme - License,Courses,Authentication,API Documentation, etc.

Just include the above 7 points that i mentioned.  

 Keep Going – You’re Doing Great!

**Comment by 10m4y** [comment]
@malaythakur changed according to your description

**Pull request merged**
